# -*- coding: utf-8 -*-
"""bucketing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rcZB4OTaOcyBXtTc-qdoYkBNepzulx4V
"""

from pyspark.sql import SparkSession

# Spark Session
spark = SparkSession.builder \
    .appName("Bucketing-Practical") \
    .config("spark.sql.shuffle.partitions", "4") \
    .enableHiveSupport() \
    .getOrCreate()

# Sample Data
data = [
    (1, "Alice", 2020),
    (2, "Bob", 2021),
    (3, "Charlie", 2022),
    (4, "David", 2023),
    (5, "Eva", 2020),
    (6, "Frank", 2021),
    (7, "George", 2022),
    (8, "Harry", 2023)
]

columns = ["user_id", "name", "year"]

df = spark.createDataFrame(data, columns)

df.show()

df.write.bucketBy(4, "user_id").sortBy("year").mode("overwrite").saveAsTable("bucketed_users")

bucketed_df = spark.table("bucketed_users")
bucketed_df.show()

