# -*- coding: utf-8 -*-
"""dataformats.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10K1iyg3zt3lw0YAq1J_DuaEIfHCOYJa6
"""

from pyspark.sql import SparkSession

# Step 1: Start SparkSession
spark = SparkSession.builder.appName("CSV Example").getOrCreate()

# Step 2: Create a sample DataFrame
data = [
    ("Aashi", 22, "F"),
    ("Raj", 30, "M"),
    ("Neha", 25, "F"),
    ("Ravi", 28, "M"),
    ("Sneha", 24, "F"),
    ("Aman", 35, "M"),
    ("Pooja", 27, "F"),
    ("Karan", 40, "M"),
    ("Simran", 23, "F"),
    ("Vikram", 31, "M"),
    ("Nisha", 26, "F"),
    ("Arjun", 29, "M"),
    ("Tina", 32, "F"),
    ("Rahul", 21, "M"),
    ("Komal", 34, "F")
]
columns = ["name", "age", "gender"]
df = spark.createDataFrame(data, columns)
df.show()

df.write.option("header", True).mode("overwrite").csv("/tmp/data_formats/csv")

csv_df = spark.read.option("header", True).csv("/tmp/data_formats/csv")

csv_df.createOrReplaceTempView("people")

result = spark.sql("SELECT * FROM people")
result.show()

maximum= spark.sql("SELECT MAX(age) FROM people")
maximum.show()

minimum = spark.sql("SELECT MIN (age) from people")
minimum.show()

greater_age = spark.sql("SELECT * FROM people WHERE age > 30")
greater_age.show()

df.write.mode("overwrite").json("/tmp/data_formats/json")

df_json = spark.read.option("multiline", False).json("/tmp/data_formats/json")
df_json.show()

df_json.createOrReplaceTempView("json_table")

df.write.mode("overwrite").parquet("/tmp/data_formats/parquet")

df_parquet=spark.read.parquet("/tmp/data_formats/parquet")
df_parquet.show()

df_parquet.createOrReplaceTempView("parquet_table")

result = spark.sql("select * from parquet_table")
result.show()

df.write.format("orc").mode("overwrite").save("/tmp/data_formats/orc")

df_orc=spark.read.format("orc").load("/tmp/data_formats/orc")
df_orc.show()

df_orc.createOrReplaceTempView("orc_table")

result = spark.sql("select * from orc_table")
result.show()

