# -*- coding: utf-8 -*-
"""file_formats.ipynb

Automatically generated by Colab. 

Original file is located at
    https://colab.research.google.com/drive/1BLdr6QLAIsz4aixrn8ncJczNBGrhZS7h
"""

from pyspark.sql import SparkSession

# Spark Session
spark = SparkSession.builder \
    .appName("Load CSV File") \
    .getOrCreate()

# Load CSV
df_csv = spark.read \
    .option("header", "true") \
    .option("inferSchema", "true") \
    .csv("file1.csv")

df_csv.show()

df_json = spark.read.json("iris-parquet.json")
df_json.show()

df_parquet = spark.read.parquet("titanic.parquet")
df_parquet.show()

from pyspark.sql import SparkSession
import sys

# Install the necessary library
!{sys.executable} -m pip install pyspark-avro

spark = SparkSession.builder \
    .appName("Read Avro File") \
    .getOrCreate()

df_avro = spark.read \
    .format("avro") \
    .load("Sample-Avro-File-Format.avro")

df_avro.show()

